load("@rules_cuda//cuda:defs.bzl", "cuda_library")

cuda_library(
    name = "tensorrt",
    srcs = [
    ],
    hdrs = [
        "NvCaffeeParser.h",
        "NvInfer.h",
        "NvInferConsistency.h",
        "NvInferConsistencyImpl.h",
        "NvInferImpl.h",
        "NvInferLegacyDims.h",
        "NvInferPlugin.h",
        "NvInferPluginUtils.h",
        "NvInferRuntime.h",
        "NvInferRuntimeBase.h",
        "NvInferRuntimeCommon.h",
        "NvInferRuntimePlugin.h",
        "NvInferSafeRuntime.h",
        "NvInferVersion.h",
        "NvOnnxConfig.h",
        "NvUffParser.h",
        "NvUtils.h",
    ],
    visibility = ["//visibility:public"],
)
